export const CharacterCategory = {
  ALL: 'all',
  CURRENCY: 'currency',
  MATH: 'math',
  ARROWS: 'arrows',
  SYMBOLS: 'symbols',
  PUNCTUATION: 'punctuation',
} as const;

export interface SpecialCharacter {
  char: string;
  name: string;
  code?: string;
}

type CharacterCategoryValue = (typeof CharacterCategory)[keyof typeof CharacterCategory];
type CharacterCategoryWithoutAll = Exclude<CharacterCategoryValue, 'all'>;

export const CHARACTERS: { [key in CharacterCategoryWithoutAll]: SpecialCharacter[] } = {
  [CharacterCategory.CURRENCY]: [
    { char: '$', name: 'Dollar sign', code: 'U+0024' },
    { char: '€', name: 'Euro sign', code: 'U+20AC' },
    { char: '£', name: 'Pound sign', code: 'U+00A3' },
    { char: '¥', name: 'Yen sign', code: 'U+00A5' },
    { char: '₹', name: 'Indian rupee sign', code: 'U+20B9' },
    { char: '¢', name: 'Cent sign', code: 'U+00A2' },
    { char: '₽', name: 'Ruble sign', code: 'U+20BD' },
    { char: '₩', name: 'Won sign', code: 'U+20A9' },
    { char: '₪', name: 'Shekel sign', code: 'U+20AA' },
    { char: '₱', name: 'Peso sign', code: 'U+20B1' },
    { char: '₦', name: 'Naira sign', code: 'U+20A6' },
    { char: '₫', name: 'Dong sign', code: 'U+20AB' },
  ],
  [CharacterCategory.MATH]: [
    { char: '±', name: 'Plus-minus sign', code: 'U+00B1' },
    { char: '×', name: 'Multiplication sign', code: 'U+00D7' },
    { char: '÷', name: 'Division sign', code: 'U+00F7' },
    { char: '≈', name: 'Almost equal to', code: 'U+2248' },
    { char: '≠', name: 'Not equal to', code: 'U+2260' },
    { char: '≤', name: 'Less than or equal to', code: 'U+2264' },
    { char: '≥', name: 'Greater than or equal to', code: 'U+2265' },
    { char: '∞', name: 'Infinity', code: 'U+221E' },
    { char: '∑', name: 'Summation', code: 'U+2211' },
    { char: '√', name: 'Square root', code: 'U+221A' },
    { char: '∫', name: 'Integral', code: 'U+222B' },
    { char: '∂', name: 'Partial differential', code: 'U+2202' },
    { char: '∆', name: 'Delta', code: 'U+2206' },
    { char: '∏', name: 'Product', code: 'U+220F' },
    { char: 'π', name: 'Pi', code: 'U+03C0' },
    { char: 'α', name: 'Alpha', code: 'U+03B1' },
    { char: 'β', name: 'Beta', code: 'U+03B2' },
    { char: 'θ', name: 'Theta', code: 'U+03B8' },
  ],
  [CharacterCategory.ARROWS]: [
    { char: '←', name: 'Left arrow', code: 'U+2190' },
    { char: '→', name: 'Right arrow', code: 'U+2192' },
    { char: '↑', name: 'Up arrow', code: 'U+2191' },
    { char: '↓', name: 'Down arrow', code: 'U+2193' },
    { char: '↔', name: 'Left-right arrow', code: 'U+2194' },
    { char: '↕', name: 'Up-down arrow', code: 'U+2195' },
    { char: '⇐', name: 'Double left arrow', code: 'U+21D0' },
    { char: '⇒', name: 'Double right arrow', code: 'U+21D2' },
    { char: '⇑', name: 'Double up arrow', code: 'U+21D1' },
    { char: '⇓', name: 'Double down arrow', code: 'U+21D3' },
    { char: '⇔', name: 'Double left-right arrow', code: 'U+21D4' },
    { char: '↖', name: 'North-west arrow', code: 'U+2196' },
    { char: '↗', name: 'North-east arrow', code: 'U+2197' },
    { char: '↘', name: 'South-east arrow', code: 'U+2198' },
    { char: '↙', name: 'South-west arrow', code: 'U+2199' },
    { char: '↺', name: 'Anticlockwise arrow', code: 'U+21BA' },
    { char: '↻', name: 'Clockwise arrow', code: 'U+21BB' },
    { char: '➜', name: 'Heavy right arrow', code: 'U+279C' },
  ],
  [CharacterCategory.SYMBOLS]: [
    { char: '©', name: 'Copyright', code: 'U+00A9' },
    { char: '®', name: 'Registered trademark', code: 'U+00AE' },
    { char: '™', name: 'Trademark', code: 'U+2122' },
    { char: '§', name: 'Section sign', code: 'U+00A7' },
    { char: '¶', name: 'Pilcrow', code: 'U+00B6' },
    { char: '†', name: 'Dagger', code: 'U+2020' },
    { char: '‡', name: 'Double dagger', code: 'U+2021' },
    { char: '•', name: 'Bullet', code: 'U+2022' },
    { char: '◦', name: 'White bullet', code: 'U+25E6' },
    { char: '●', name: 'Black circle', code: 'U+25CF' },
    { char: '○', name: 'White circle', code: 'U+25CB' },
    { char: '■', name: 'Black square', code: 'U+25A0' },
    { char: '□', name: 'White square', code: 'U+25A1' },
    { char: '▪', name: 'Small black square', code: 'U+25AA' },
    { char: '▫', name: 'Small white square', code: 'U+25AB' },
    { char: '★', name: 'Black star', code: 'U+2605' },
    { char: '☆', name: 'White star', code: 'U+2606' },
    { char: '♠', name: 'Spade', code: 'U+2660' },
    { char: '♣', name: 'Club', code: 'U+2663' },
    { char: '♥', name: 'Heart', code: 'U+2665' },
    { char: '♦', name: 'Diamond', code: 'U+2666' },
    { char: '✓', name: 'Check mark', code: 'U+2713' },
    { char: '✗', name: 'Ballot X', code: 'U+2717' },
    { char: '☐', name: 'Ballot box', code: 'U+2610' },
  ],
  [CharacterCategory.PUNCTUATION]: [
    { char: '‚', name: 'Single low-9 quotation mark', code: 'U+201A' },
    { char: '„', name: 'Double low-9 quotation mark', code: 'U+201E' },
    { char: "'", name: 'Left single quotation mark', code: 'U+2018' },
    { char: "'", name: 'Right single quotation mark', code: 'U+2019' },
    { char: '"', name: 'Left double quotation mark', code: 'U+201C' },
    { char: '"', name: 'Right double quotation mark', code: 'U+201D' },
    { char: '«', name: 'Left guillemet', code: 'U+00AB' },
    { char: '»', name: 'Right guillemet', code: 'U+00BB' },
    { char: '‹', name: 'Single left angle quotation', code: 'U+2039' },
    { char: '›', name: 'Single right angle quotation', code: 'U+203A' },
    { char: '—', name: 'Em dash', code: 'U+2014' },
    { char: '–', name: 'En dash', code: 'U+2013' },
    { char: '…', name: 'Ellipsis', code: 'U+2026' },
    { char: '‰', name: 'Per mille', code: 'U+2030' },
    { char: '¿', name: 'Inverted question mark', code: 'U+00BF' },
    { char: '¡', name: 'Inverted exclamation mark', code: 'U+00A1' },
    { char: '·', name: 'Middle dot', code: 'U+00B7' },
    { char: '‧', name: 'Hyphenation point', code: 'U+2027' },
  ],
};

export type CharacterCategory = (typeof CharacterCategory)[keyof typeof CharacterCategory];

