import { DocumentEngineConfig } from '@phuong-tran-redoc/document-engine-core';

export const DefaultEditorConfig: Partial<DocumentEngineConfig> = {
  link: {
    openOnClick: false,
    defaultProtocol: 'https',
    enableClickSelection: true,
    shouldAutoLink: (url) =>
      url.startsWith('http://') || url.startsWith('https://') || url.startsWith('mailto:') || url.startsWith('tel:'),
  },
  blockquote: false,
  heading: false,
  bold: false,
  italic: false,
  underline: false,
  strike: false,
  list: false,
  codeBlock: false,
  code: false,
  undoRedo: false,
  textStyleKit: false,
  tables: false,
  characterCount: false,
  subscript: false,
  superscript: false,
  textAlign: false,
  image: false,
  placeholder: false,
  pageBreak: false,
  resetFormat: false,
  indent: false,
  clearContent: false,
  textCase: false,
  dynamicField: false,
  specialCharacters: false,
  showFooter: false,
  fontSize: false,
  lineHeight: false,
  editable: true,
  restrictedEditing: false,
  showToolbar: true,
};
